#!/bin/bash

# Create main directory
mkdir -p QuantilyxDoc

# Create subdirectories
mkdir -p QuantilyxDoc/cmake
mkdir -p QuantilyxDoc/build-scripts
mkdir -p QuantilyxDoc/debian
mkdir -p QuantilyxDoc/rpm
mkdir -p QuantilyxDoc/flatpak
mkdir -p QuantilyxDoc/resources/images
mkdir -p QuantilyxDoc/resources/translations
mkdir -p QuantilyxDoc/resources/themes
mkdir -p QuantilyxDoc/resources/templates
mkdir -p QuantilyxDoc/resources/fonts
mkdir -p QuantilyxDoc/resources/scripts
mkdir -p QuantilyxDoc/src/core
mkdir -p QuantilyxDoc/src/formats/pdf
mkdir -p QuantilyxDoc/src/formats/epub
mkdir -p QuantilyxDoc/src/formats/djvu
mkdir -p QuantilyxDoc/src/formats/comic
mkdir -p QuantilyxDoc/src/formats/postscript
mkdir -p QuantilyxDoc/src/formats/xps
mkdir -p QuantilyxDoc/src/formats/chm
mkdir -p QuantilyxDoc/src/formats/markdown
mkdir -p QuantilyxDoc/src/formats/fictionbook
mkdir -p QuantilyxDoc/src/formats/mobi
mkdir -p QuantilyxDoc/src/formats/image
mkdir -p QuantilyxDoc/src/formats/cad
mkdir -p QuantilyxDoc/src/formats/office
mkdir -p QuantilyxDoc/src/ui
mkdir -p QuantilyxDoc/src/ui/dialogs
mkdir -p QuantilyxDoc/src/ui/widgets
mkdir -p QuantilyxDoc/src/ui/preferences
mkdir -p QuantilyxDoc/src/ui/tools
mkdir -p QuantilyxDoc/src/annotations
mkdir -p QuantilyxDoc/src/editing
mkdir -p QuantilyxDoc/src/editing/richtext
mkdir -p QuantilyxDoc/src/editing/typography
mkdir -p QuantilyxDoc/src/editing/formatting
mkdir -p QuantilyxDoc/src/editing/paragraph
mkdir -p QuantilyxDoc/src/editing/lists
mkdir -p QuantilyxDoc/src/editing/tables
mkdir -p QuantilyxDoc/src/editing/drawing
mkdir -p QuantilyxDoc/src/editing/images
mkdir -p QuantilyxDoc/src/editing/layout
mkdir -p QuantilyxDoc/src/editing/references
mkdir -p QuantilyxDoc/src/editing/review
mkdir -p QuantilyxDoc/src/editing/mailmerge
mkdir -p QuantilyxDoc/src/recognition
mkdir -p QuantilyxDoc/src/ocr
mkdir -p QuantilyxDoc/src/search
mkdir -p QuantilyxDoc/src/export
mkdir -p QuantilyxDoc/src/print
mkdir -p QuantilyxDoc/src/security
mkdir -p QuantilyxDoc/src/comparison
mkdir -p QuantilyxDoc/src/scanner
mkdir -p QuantilyxDoc/src/metadata
mkdir -p QuantilyxDoc/src/library
mkdir -p QuantilyxDoc/src/workspace
mkdir -p QuantilyxDoc/src/presentation
mkdir -p QuantilyxDoc/src/automation
mkdir -p QuantilyxDoc/src/analytics
mkdir -p QuantilyxDoc/src/templates
mkdir -p QuantilyxDoc/src/network
mkdir -p QuantilyxDoc/src/versioncontrol
mkdir -p QuantilyxDoc/src/clipboard
mkdir -p QuantilyxDoc/src/reading
mkdir -p QuantilyxDoc/src/bookmarks
mkdir -p QuantilyxDoc/src/sanitization
mkdir -p QuantilyxDoc/src/pagemanagement
mkdir -p QuantilyxDoc/src/optimization
mkdir -p QuantilyxDoc/src/repair
mkdir -p QuantilyxDoc/src/assembly
mkdir -p QuantilyxDoc/src/portfolio
mkdir -p QuantilyxDoc/src/measurement
mkdir -p QuantilyxDoc/src/timeline
mkdir -p QuantilyxDoc/src/formbuilder
mkdir -p QuantilyxDoc/src/review
mkdir -p QuantilyxDoc/src/multilingual
mkdir -p QuantilyxDoc/src/cli
mkdir -p QuantilyxDoc/src/systemintegration
mkdir -p QuantilyxDoc/src/design
mkdir -p QuantilyxDoc/src/collaboration
mkdir -p QuantilyxDoc/src/tutorials
mkdir -p QuantilyxDoc/src/feedback
mkdir -p QuantilyxDoc/src/plugins
mkdir -p QuantilyxDoc/src/web
mkdir -p QuantilyxDoc/src/utils
mkdir -p QuantilyxDoc/src/tests
mkdir -p QuantilyxDoc/plugins/ai-assistant
mkdir -p QuantilyxDoc/plugins/universal-converter
mkdir -p QuantilyxDoc/plugins/advanced-ocr
mkdir -p QuantilyxDoc/plugins/data-extraction
mkdir -p QuantilyxDoc/plugins/version-control
mkdir -p QuantilyxDoc/plugins/accessibility
mkdir -p QuantilyxDoc/plugins/forensics
mkdir -p QuantilyxDoc/plugins/publishing
mkdir -p QuantilyxDoc/plugins/multimedia
mkdir -p QuantilyxDoc/plugins/research-tools
mkdir -p QuantilyxDoc/plugins/drm-security
mkdir -p QuantilyxDoc/plugins/macro-system
mkdir -p QuantilyxDoc/plugins/mobile-companion
mkdir -p QuantilyxDoc/plugins/plugin-marketplace
mkdir -p QuantilyxDoc/web-interface/public/css
mkdir -p QuantilyxDoc/web-interface/public/js
mkdir -p QuantilyxDoc/web-interface/public/img/icons
mkdir -p QuantilyxDoc/web-interface/public/img/logos
mkdir -p QuantilyxDoc/web-interface/templates
mkdir -p QuantilyxDoc/web-interface/api
mkdir -p QuantilyxDoc/docs/user-manual/css
mkdir -p QuantilyxDoc/docs/user-manual/js
mkdir -p QuantilyxDoc/docs/user-manual/images
mkdir -p QuantilyxDoc/docs/user-manual/getting-started
mkdir -p QuantilyxDoc/docs/user-manual/viewing
mkdir -p QuantilyxDoc/docs/user-manual/editing
mkdir -p QuantilyxDoc/docs/user-manual/annotations
mkdir -p QuantilyxDoc/docs/user-manual/ocr
mkdir -p QuantilyxDoc/docs/user-manual/security
mkdir -p QuantilyxDoc/docs/user-manual/conversion
mkdir -p QuantilyxDoc/docs/user-manual/collaboration
mkdir -p QuantilyxDoc/docs/user-manual/automation
mkdir -p QuantilyxDoc/docs/user-manual/preferences
mkdir -p QuantilyxDoc/docs/user-manual/plugins
mkdir -p QuantilyxDoc/docs/user-manual/web-interface
mkdir -p QuantilyxDoc/docs/user-manual/troubleshooting
mkdir -p QuantilyxDoc/docs/user-manual/reference
mkdir -p QuantilyxDoc/docs/user-manual/appendix
mkdir -p QuantilyxDoc/docs/developer/api
mkdir -p QuantilyxDoc/docs/developer/plugins
mkdir -p QuantilyxDoc/docs/translations/fr
mkdir -p QuantilyxDoc/docs/translations/de
mkdir -p QuantilyxDoc/docs/translations/zh
mkdir -p QuantilyxDoc/docs/translations/es
mkdir -p QuantilyxDoc/docs/translations/ru
mkdir -p QuantilyxDoc/tests/unit
mkdir -p QuantilyxDoc/tests/integration
mkdir -p QuantilyxDoc/tests/fixtures/sample_pdfs
mkdir -p QuantilyxDoc/tests/fixtures/test_images
mkdir -p QuantilyxDoc/tests/fixtures/test_documents
mkdir -p QuantilyxDoc/scripts
mkdir -p QuantilyxDoc/config/user-profiles
mkdir -p QuantilyxDoc/data/ocr-languages
mkdir -p QuantilyxDoc/data/dictionaries
mkdir -p QuantilyxDoc/data/certificates
mkdir -p QuantilyxDoc/examples/sample-documents
mkdir -p QuantilyxDoc/examples/scripts
mkdir -p QuantilyxDoc/examples/plugins/example-plugin
mkdir -p QuantilyxDoc/packaging/desktop
mkdir -p QuantilyxDoc/packaging/icons/hicolor
mkdir -p QuantilyxDoc/packaging/man
mkdir -p QuantilyxDoc/packaging/mime

echo "Directory structure created successfully."
